name: pokeme
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^3.0.4
  flutter_timezone: ^1.0.8
  flutter_local_notifications: ^15.1.1
  rxdart: ^0.27.7
  flutter_slidable: ^3.0.1
  sqflite: ^2.0.2+1
  intl: ^0.17.0
  dotted_border: ^2.1.0
  flutter_analog_clock: ^1.0.3
  provider: ^6.1.1
  android_intent: ^2.0.2
  file_picker: ^6.1.1 
  path_provider: ^2.1.1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
